[build]
  publish = "dist"
  command = "npm ci --include=dev && npm run build"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  environment = { NODE_ENV = "production" }

[context.deploy-preview]
  environment = { NODE_ENV = "development" }
  command = "npm ci --include=dev && npm run build:dev"

[context.branch-deploy]
  environment = { NODE_ENV = "development" }
  command = "npm ci --include=dev && npm run build:dev"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https: data:; style-src 'self' 'unsafe-inline' https: https://fonts.googleapis.com; img-src 'self' https: data: blob: https://ui-avatars.com; font-src 'self' https: data: https://fonts.gstatic.com; connect-src 'self' https: wss: ws: https://*.supabase.co wss://*.supabase.co; media-src 'self' https: blob:; object-src 'none'; frame-src 'self' https:; worker-src 'self' blob:;"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"